COHORT_HOME = ../../..

# Library name
lbase = LoopChain

# Base directory
base_dir = .

# Other directories with required source code
src_dirs = 

# Libraries
libnames = BaseTools Parser

include $(COHORT_HOME)/mk/Make.example
