COHORT_HOME = ..

# Executable name
ebase = omplc_tool

# Base directory
base_dir = .

# Other directories with required source code
src_dirs =

# Libraries
libnames = LoopChain Parser BaseTools

include $(COHORT_HOME)/mk/Make.example
