COHORT_HOME = ../../..

# Library name
lbase = Parser

# Base directory
base_dir = .

# Other directories with required source code
src_dirs = 

# Libraries
libnames = BaseTools

include $(COHORT_HOME)/mk/Make.example
